import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useAccount } from 'wagmi'
import { Alchemy,Network } from "alchemy-sdk";



const inter = Inter({ subsets: ['latin'] })

let numNfts = 0;


export default function similar_to_me() {


  const {address, connector} = useAccount();

  

  const alchemyConfig = {
    apiKey: "_G2d1vbQhp9CpDFEMQaAqB6xtUlXQMqq",
    network: Network.ETH_MAINNET,
  };

  const alchemy = new Alchemy(alchemyConfig);
    
  const main = async () => {
    
    // Get all NFTs
    const nfts = await alchemy.nft.getNftsForOwner(address);
    // Print NFTs
    numNfts = nfts["totalCount"];
    const nftList = nfts["ownedNfts"];

  
    let i = 1;
  
    for (let nft of nftList) {
      console.log(`${i}. ${nft.title}`);
      i++;
    }
  };

  const runMain = async () => {
    try {
      await main();
      
    } catch (error) {
      console.log(error);
      
    }
  };
  
  runMain();

    return (
        <>
          <Head>
            <title>similar to me Group</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <h1>similar to me</h1>
            
            <p>Total NFTs owned by {address}: {numNfts} </p>
              <Link href="/">Topへ</Link>
              
          </main>
        </>
      )
    
}