import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useAccount } from 'wagmi'
import { Alchemy,Network } from "alchemy-sdk";


const inter = Inter({ subsets: ['latin'] });


let numNfts = 0;
let score = 0;


export default function similar_to_me() {



const {address, connector} = useAccount();


const alchemyConfig = {
  apiKey: "_G2d1vbQhp9CpDFEMQaAqB6xtUlXQMqq",
  network: Network.ETH_MAINNET,
};

const alchemy = new Alchemy(alchemyConfig);



  const main = async () => {
    
    // Get all NFTs
    const nfts = await alchemy.nft.getNftsForOwner(address);
    // Print NFTs
    numNfts = nfts["totalCount"];
    let nftList = nfts["ownedNfts"];

    let i = 1;
    for (let nft of nftList) {
      console.log(`${i}. ${nft.title}, ${nft.contract.address}`);
      i++;


      if (nft.contract.address === "0x8f96b11707aa7274634b54076735c9dc06648397"){
        score += 10;
      }else if(nft.contract.address === "0x495f947276749ce646f68ac8c248420045cb7b5e"){
        score += 10;
      }else if(nft.contract.address === "0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85"){
        score += 10;
      }else if(nft.contract.address === "0xca6d7604ae55ba1ba864c26692a91979f25cdb96"){
        score += 10;
      }else if(nft.contract.address === "0xf8527def19d2d40226e5ebccf3cd5a27cca63efa"){
        score += 10;
      }

      console.log(score);
    }
    
  };

  const runMain = async () => {
    try {
      await main();
      
    } catch (error) {
      console.log(error);
      
    }
  };
  
    return (
        <>
          <Head>
            <title>similar to me Group</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <h1>similar to harutokakizawa.eth</h1>
            
            <div>
              <button onClick={runMain}>スコア算出</button>
              <a>一回しか押さないでください</a>
              <p>score: {score}</p>
            </div>


            <h3>参照コントラクト</h3>
            <a href='https://etherscan.io/address/0x8f96b11707aa7274634b54076735c9dc06648397'>0x8f96b11707aa7274634b54076735c9dc06648397</a>
            <a href='https://etherscan.io/address/0x495f947276749ce646f68ac8c248420045cb7b5e'>0x495f947276749ce646f68ac8c248420045cb7b5e</a>
            <a href='https://etherscan.io/address/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85'>0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85</a>
            <a href='https://etherscan.io/address/0xca6d7604ae55ba1ba864c26692a91979f25cdb96'>0xca6d7604ae55ba1ba864c26692a91979f25cdb96</a>
            <a href='https://etherscan.io/address/0xf8527def19d2d40226e5ebccf3cd5a27cca63efa'>0xf8527def19d2d40226e5ebccf3cd5a27cca63efa</a>







            
            

              <Link href="/">Topへ</Link>
              
          </main>
        </>
      )
    
}