import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { ConnectButton } from '@rainbow-me/rainbowkit'
import { useNetwork } from 'wagmi'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const  {chain, chains}  = useNetwork();


  return (
    <>
      <Head>
        <title>NFT Grouping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <Link href="/Groups/socials">socials</Link>
          <ConnectButton />
          {chain && <h1 className={styles.center}>Welcome to {chain.name} World</h1>}
      </main>
    </>
  )
}
