import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
<<<<<<< HEAD
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { ConnectButton } from '@rainbow-me/rainbowkit'
import { useAccount, useNetwork } from 'wagmi'
import { Alchemy,Network } from "alchemy-sdk";
=======
import styles from '../styles/Home.module.css'
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useNetwork } from 'wagmi'
import Link from 'next/link';




>>>>>>> origin/main

const inter = Inter({ subsets: ['latin'] })


<<<<<<< HEAD
export default function Home() {

  const  {chain, chains}  = useNetwork();

  const {address, connector} = useAccount();

  const alchemyConfig = {
    apiKey: process.env.ALCHEMY_ID,
    network: Network.ETH_MAINNET,
  };

  const alchemy = new Alchemy(alchemyConfig);
=======



export default function Home() {
  const  {chain, chains}  = useNetwork();

>>>>>>> origin/main

  return (
    <>
      <Head>
<<<<<<< HEAD
        <title>NFT Grouping</title>
=======
        <title>Create Next App</title>
>>>>>>> origin/main
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
<<<<<<< HEAD
      {chain && <h1>{address},Welcome to {chain.name} World</h1>}
          <Link href="/Groups/similar_to_me">similar to me</Link>
          <ConnectButton />
          
=======
        <div className={styles.description}>
          

          <Link href="/Groups/socials">socials</Link>
          <ConnectButton />
          
        </div>

        
          {chain && <h1 className={styles.center}>Welcome to {chain.name} World</h1>}
          
        
          

          
        
>>>>>>> origin/main
      </main>
    </>
  )
}
<<<<<<< HEAD
=======

>>>>>>> origin/main
