import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { ConnectButton } from '@rainbow-me/rainbowkit'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  

  return (
    <>
      <Head>
        <title>NFT Grouping</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>ルール一覧</h1>
      
          <Link href="/Groups/similar_to_me">similar to harutokakizawa.eth</Link>
          <ConnectButton />
          
      </main>
    </>
  )
}
